### ISSUE TITLE
Consider aarch64 build

### ISSUE THREAD

**Issue by calhix** [wojnilowicz/ungoogled-chromium-copr#1]
Hello, thank you for providing this as the flatpak build is quite heavy, currently for a lot of us Asahi Linux users we only have Brave and Chromium as options. Would you perhaps consider providing an aarch64 build?

**Comment by wojnilowicz** [comment]
Hi, you're welcome. As for the aarch64 build, then it is now available for Fedora 39 and 40. Please confirm that it works. I cannot do it myself.

**Comment by calhix** [comment]
It works wonderfully thank you so much!

-------- Original Message --------

**Comment by wojnilowicz** [comment]
I'm happy to hear that 🙂 Thanks for the publicity you made on reddit. My name is a bit misspelled there though 🙄
