### ISSUE TITLE
I Can't use videoconference on the COPR version, but i can with the Flatpak one

### ISSUE THREAD

**Issue by AAguiarCAM** [wojnilowicz/ungoogled-chromium-copr#2]
I have no idea on how to send an issue, i've never done it before, sorry for inconvenients.

I am having trouble accessing a videoconference website using this COPR version.

the website is a room from the https://webapp.lifesize.com/

i am using the version 124.0.6367.60 (Official Build, ungoogled-chromium) Ungoogled Chromium 64 bits

the main problem is not just the it doesnt work, but the fact that the flatpak version works flawelessly. the flatpak version is the same as the COPR

i am using Fedora 40, and the problem was already present on Fedora 39

**Comment by wojnilowicz** [comment]
No problem. You've came to the right place.

As for the videoconference website not working then does it work with Fedora's Chromium for you?

The thing is that I use Fedora's Chromium as a base for Ungoogled Chromium, and the flatpak version uses probably official Chromium as a base for Ungoogled Chromium. Ungoogled Chromium patches work for both. AFAIK Fedora removes some codecs from its Chromium so maybe that's the culprit.

**Comment by AAguiarCAM** [comment]
Oh, i checked with regular Chromium. Didn't work either.

weird. i have the multimedia from rpm fusion installed. shouldnt it work?

do you have any suggestion for me? the flatpak version takes twice as long to load. :(

**Comment by wojnilowicz** [comment]
> Oh, i checked with regular Chromium. Didn't work either.

Then unfortunately I can't offer anything more.

> weird. i have the multimedia from rpm fusion installed. shouldnt it work?

As you see, it doesn't.

> do you have any suggestion for me? the flatpak version takes twice as long to load. :(

If you have to stick with Fedora then nothing comes to my mind.

**Comment by AAguiarCAM** [comment]
Thank you! :smile:

**Comment by wojnilowicz** [comment]
Could [this](https://bugzilla.redhat.com/show_bug.cgi?id=2277458) help your case, be it regular or ungoogled one?
